definitions:
  domain.Subscription:
    properties:
      end_date:
        example: 12-2026
        type: string
      id:
        example: 10
        type: integer
      price:
        example: 500
        type: integer
      service_name:
        example: Spotify Premium
        type: string
      start_date:
        example: 01-2026
        type: string
      user_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  handler.CreateSubscriptionRequest:
    properties:
      end_date:
        example: 12-2026
        type: string
      price:
        example: 500
        type: integer
      service_name:
        example: Spotify Premium
        type: string
      start_date:
        example: 01-2026
        type: string
      user_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  handler.ExtendInput:
    properties:
      end_date:
        example: 12-2027
        type: string
      price:
        example: 600
        type: integer
    type: object
  handler.TotalCostResponse:
    properties:
      details:
        example:
        - 'Spotify Premium: 6000'
        items:
          type: string
        type: array
      period:
        additionalProperties:
          type: string
        type: object
      total_cost:
        example: 6000
        type: integer
      warning:
        type: string
    type: object
info:
  contact: {}
  description: The test task for "effective mobile"
  title: Effective Task
  version: "1.0"
paths:
  /subscriptions:
    get:
      parameters:
      - description: User UUID
        in: query
        name: user_id
        required: true
        type: string
      - description: Service filter
        in: query
        name: service_name
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Min price
        in: query
        name: min_price
        type: integer
      - description: Max price
        in: query
        name: max_price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Subscription'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      parameters:
      - description: Subscription info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              format: int64
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
      summary: Create subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete subscription
      tags:
      - subscriptions
    get:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Subscription'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get subscription details
      tags:
      - subscriptions
  /subscriptions/{id}/extend:
    put:
      consumes:
      - application/json
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: integer
      - description: New data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.ExtendInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Extend subscription
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      parameters:
      - description: User UUID
        in: query
        name: user_id
        required: true
        type: string
      - description: Start date (MM-YYYY)
        in: query
        name: from
        required: true
        type: string
      - description: End date (MM-YYYY)
        in: query
        name: to
        required: true
        type: string
      - description: Service filter(не обязатльно)
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TotalCostResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Calculate total cost
      tags:
      - subscriptions
swagger: "2.0"
