definitions:
  domain.Subscription:
    properties:
      end_date:
        example: 12-2026
        type: string
      id:
        example: 10
        type: integer
      price:
        example: 500
        type: integer
      service_name:
        example: Spotify Premium
        type: string
      start_date:
        example: 01-2026
        type: string
      user_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  handler.ExtendInput:
    properties:
      end_date:
        example: 12-2027
        type: string
      price:
        example: 600
        type: integer
    type: object
info:
  contact: {}
  description: The test task for "effective mobile"
  title: Effective Task
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Получить список подписок пользователя с фильтрами / Get user subscriptions
        with filters
      parameters:
      - description: UUID пользователя
        example: 550e8400-e29b-41d4-a716-446655440000
        in: query
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - description: Лимит
        example: 5
        in: query
        name: limit
        type: integer
      - description: Смещение
        example: 3
        in: query
        name: offset
        type: integer
      - description: Мин. цена
        example: 1000
        in: query
        name: min_price
        type: integer
      - description: Макс. цена
        example: 1300
        in: query
        name: max_price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Subscription'
            type: array
      summary: Список подписок / List subscriptions
    post:
      consumes:
      - application/json
      description: Добавляет новую запись о подписке пользователя / Adds a new subscription
        record
      parameters:
      - description: Данные подписки / Subscription data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Subscription'
      produces:
      - application/json
      responses:
        "201":
          description: id новой записи
          schema:
            additionalProperties:
              format: int64
              type: integer
            type: object
        "400":
          description: Ошибка валидации / Validation error
          schema:
            type: string
        "409":
          description: Подписка уже существует / Subscription already exists
          schema:
            type: string
      summary: Создать подписку / Create subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Удаляет запись о подписке по ID / Deletes subscription record by
        ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 'status: deleted'
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Не найдено / Not found
          schema:
            type: string
      summary: Удалить подписку / Delete subscription
      tags:
      - subscriptions
    get:
      description: Получение данных подписки по её ID / Get subscription details by
        ID
      parameters:
      - description: ID подписки / Subscription ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Subscription'
        "404":
          description: Не найдено / Not found
          schema:
            type: string
      summary: Получить подписку / Get subscription
      tags:
      - subscriptions
  /subscriptions/{id}/extend:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID подписки
        example: 1
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.ExtendInput'
      produces:
      - application/json
      responses:
        "200":
          description: 'example: {status: success}'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Продлить подписку / Extend subscription
      tags:
      - subscriptions
  /subscriptions/total:
    get:
      parameters:
      - description: UUID пользователя
        example: 550e8400-e29b-41d4-a716-446655440000
        in: query
        name: user_id
        required: true
        type: string
      - description: Начало (MM-YYYY)
        example: 01-2026
        in: query
        name: from
        required: true
        type: string
      - description: Конец (MM-YYYY)
        example: 12-2026
        in: query
        name: to
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Пример: {total_cost: 30000, details: [...]}'
          schema:
            additionalProperties: true
            type: object
      summary: Суммарная стоимость / Total cost
      tags:
      - subscriptions
swagger: "2.0"
